name: Deploy

on:
  push:
    branches: [production]

jobs:
  call-build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: call-build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PRD_PROJECT_DIR }}
            git fetch origin
            git reset --hard origin/staging
            composer install --no-dev --optimize-autoloader
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt install -y nodejs/nodistro
            npm ci
            npm run build
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link
            chmod -R ug+rwX storage storage/framework
            echo "✅ Skipping chown - already owned properly"
            sudo supervisorctl restart inertia-ssr
            sudo supervisorctl restart octane-frankenphp
